### ISSUE TITLE
Why the dependencies ?

### ISSUE THREAD

**Issue by anisse** [azavea/ansible-golang#6]
I was wondering why there was three dependencies in this playbook ?

**Comment by hectcastro** [comment]
Trying to think back, I'm not entirely sure why `build-essential` is a dependency. It may have been from a time where we were building Go from source. Light testing without it isn't revealing any issues, so I think it can be removed.

As far as Mercurial and Git go, in practice, many of the dependencies retrieved by `go get` require Mercurial and Git to be present. Trading off some convenience there for common cases vs. leanness.

**Comment by anisse** [comment]
Thanks for your answer. IMHO golang can be used without git/hg, but it's true that "go get" would be seriously crippled. I understand the trade-off.

**Comment by hectcastro** [comment]
FYI, the `build-essential` removal was just merged. Thanks for opening the issue about it.
